webserver:
  image: wordpress
  ports:
    - "80:80"
  volumes:
    - ./wordpress/wp_html:/var/www/html
    - ./data:/data
  links:
    - "dbserver:mysql"
dbserver:
  image: mysql
  volumes_from:
   - dataonly
  environment:
    MYSQL_ROOT_PASSWORD: password

